server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
          - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth-service
                fallbackUri: forward:/authfallback
        - id: quote-service
          uri: lb://quote-service
          predicates:
          - Path=/quote/**
          filters:
            - name: CircuitBreaker
              args:
                name: quote-service
                fallbackUri: forward:/quotefallback

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 5000
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true

management:
  endpoints:
    web:
      exposure:
        include: "*"