server:
  port: 9000

spring:
  config:
    import: optional:configserver:http://config-service
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
          - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/userfallback
        - id: quote-service
          uri: lb://quote-service
          predicates:
          - Path=/quote/**
          filters:
            - name: CircuitBreaker
              args:
                name: quote-service
                fallbackUri: forward:/quotefallback

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 5000
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
